version: '3.7'
services:
  admin:
    tty: true
    build: 
      context: /home/dlabs/decemberLabs/capacitacion-admin
    command: yarn start
    ports:
      - '5001:5001'
    volumes:
      - /home/dlabs/decemberLabs/capacitacion-admin/src:/app/capacitacion-admin/src
      - /home/dlabs/decemberLabs/capacitacion-admin/public:/app/capacitacion-admin/public
