version: '3.7'
networks:
  default:
    external:
      name: pis-septemberlabs
services:
  admin:
    tty: true
    build:
      context: ${PARENT_PWD}/capacitacion-admin
    container_name: pis-septemberlabs_admin
    command: yarn start
    ports:
      - '5001:5001'
    volumes:
      - ${PARENT_PWD}/capacitacion-admin/src:/app/capacitacion-admin/src
      - ${PARENT_PWD}/capacitacion-admin/public:/app/capacitacion-admin/public
